/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_contact_app;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author shane
 */
public class MyContactsForm extends javax.swing.JFrame {

    /**
     * Creates new form MyContactsForm
     */
    
    
    //CREATING LOCAL VARIABLE FOR BROWSE FUNCTION - SEE BROWSE AREA.
    String imagePth = null;
    //Connects with login page to display the current user ID 
    public static int currentUserId;
    String EMAIL_PATTERN;
    
    public MyContactsForm() {
       
        initComponents();
        populateJtable();
        //DECORATING THE TABLE OF CONTACTS
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.ORANGE);
        jTable1.setSelectionBackground(Color.DARK_GRAY);
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.BLACK);
        
        th.setFont(new Font("Tahoma", Font.BOLD, 14));
        System.out.println(currentUserId+ "From Contact");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jLabelContactPic = new javax.swing.JLabel();
        jButtonBrowseImage = new javax.swing.JButton();
        jButtonDeleteContact = new javax.swing.JButton();
        jTextFieldFname = new javax.swing.JTextField();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddContact = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonEditContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Contacts");

        jLabelUserPic.setBackground(new java.awt.Color(255, 0, 0));
        jLabelUserPic.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setOpaque(true);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelUsername))
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jLabelUserPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 140, 110, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Address");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(450, 260, 100, 22);

        jTextFieldEmail.setEditable(true);
        jTextFieldEmail.setBackground(new java.awt.Color(200, 247, 197));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(170, 240, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Phone");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 190, 110, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 240, 110, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Group");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 290, 110, 22);

        jComboBoxGroup.setBackground(new java.awt.Color(200, 247, 197));
        jComboBoxGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family", "Friends", "Work" }));
        jPanel2.add(jComboBoxGroup);
        jComboBoxGroup.setBounds(170, 290, 190, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(410, 72, 60, 270);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("ID:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 50, 60, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Profile Picture:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(440, 90, 140, 22);

        jTextAreaAddress.setBackground(new java.awt.Color(200, 247, 197));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jTextAreaAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(590, 250, 280, 100);

        jLabelContactPic.setBackground(new java.awt.Color(204, 255, 255));
        jLabelContactPic.setOpaque(true);
        jPanel2.add(jLabelContactPic);
        jLabelContactPic.setBounds(590, 80, 220, 150);

        jButtonBrowseImage.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBrowseImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBrowseImage);
        jButtonBrowseImage.setBounds(820, 90, 77, 25);

        jButtonDeleteContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonDeleteContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteContact.setText("Delete");
        jButtonDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeleteContact);
        jButtonDeleteContact.setBounds(950, 310, 110, 40);

        jTextFieldFname.setEditable(true);
        jTextFieldFname.setBackground(new java.awt.Color(200, 247, 197));
        jTextFieldFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jTextFieldFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFnameKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldFname);
        jTextFieldFname.setBounds(170, 90, 190, 40);

        jTextFieldLname.setEditable(true);
        jTextFieldLname.setBackground(new java.awt.Color(200, 247, 197));
        jTextFieldLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jTextFieldLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLnameKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldLname);
        jTextFieldLname.setBounds(170, 140, 190, 40);

        jTextFieldPhone.setEditable(true);
        jTextFieldPhone.setBackground(new java.awt.Color(200, 247, 197));
        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(170, 190, 190, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 370, 1150, 440);

        jButtonAddContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonAddContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact.setText("Add");
        jButtonAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddContact);
        jButtonAddContact.setBounds(880, 250, 110, 40);

        jTextFieldId.setEditable(true);
        jTextFieldId.setBackground(new java.awt.Color(200, 247, 197));
        jTextFieldId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldId);
        jTextFieldId.setBounds(170, 40, 190, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("First Name:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 90, 110, 22);

        jButtonEditContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonEditContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditContact.setText("Edit");
        jButtonEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditContact);
        jButtonEditContact.setBounds(1020, 250, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //THIS CALLS FROM CONTACT QUERY 
    public void populateJtable(){
        
        contactQuery cq = new contactQuery();
            ArrayList<contact> ctList = cq.contactList(currentUserId);
            String[] colNames = {"Id","First Name","Last Name","Group","Phone", "Email", "Address", "Image"};
            Object[][]rows = new Object[ctList.size()][8];
            
            for(int i = 0; i < ctList.size(); i++){
                rows[i][0] = ctList.get(i).getCid();
                rows[i][1] = ctList.get(i).getFname();
                rows[i][2] = ctList.get(i).getLname();
                rows[i][3] = ctList.get(i).getGroupc();
                rows[i][4] = ctList.get(i).getPhone();
                rows[i][5] = ctList.get(i).getEmail();
                rows[i][6] = ctList.get(i).getAddress();
                
                ImageIcon pic = new ImageIcon(new ImageIcon
        
                                           (ctList.get(i).getPic())
                                            .getImage()
                                            .getScaledInstance(110, 90, Image.SCALE_SMOOTH));
                
                rows[i][7] = pic;
            }
            //CREATES TABLE AND SETS THE WIDTH OF EACH ROW AND HEIGHT IN ABOVE STATEMENT.
            MyModel mmd = new MyModel(rows, colNames);
            jTable1.setModel(mmd);
            
            jTable1.setRowHeight(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);
    }
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed
        // TODO add your handling code here:
        Myfunc mf = new Myfunc();
       imagePth = mf.browseImage(jLabelContactPic);
       System.out.println(imagePth);
    }//GEN-LAST:event_jButtonBrowseImageActionPerformed


   
    
    
    
    private void jButtonDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContactActionPerformed
        // TODO add your handling code here:
        int id = Integer.valueOf(jTextFieldId.getText());
        contactQuery cq = new contactQuery();
        cq.deleteContact(id);
       refreshJtable();
       clearFields();
           
      
        
            
    }//GEN-LAST:event_jButtonDeleteContactActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        //DISPLAY SELECTED TABLE ROW DATA into the textfields above it
        //GET SELECTED ROW DATA
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldFname.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextFieldLname.setText(jTable1.getValueAt(rowIndex, 2).toString());
        
        //same for group, phone, email etc
        jComboBoxGroup.setSelectedItem(jTable1.getValueAt(rowIndex, 3));
        jTextFieldPhone.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextFieldId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextAreaAddress.setText(jTable1.getValueAt(rowIndex, 6).toString());
        //SHOWS PICTURE WHEN USER IS CLICKED ON FROM TABLE
        Image pic = ((ImageIcon)jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(), jLabelContactPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelContactPic.setIcon(img);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContactActionPerformed
        // TODO add your handling code here:
         String fname = jTextFieldFname.getText();
       String lname = jTextFieldLname.getText();
       String phone = jTextFieldPhone.getText();
       String address = jTextAreaAddress.getText();
       String email = jTextFieldEmail.getText();
       String groupc = jComboBoxGroup.getSelectedItem().toString();
       
       
       
       //CHECK IF ALL FIELDS ARE FILLED OUT WHEN ADDING - VALIDATION.
       byte[] img = null;
       
       
       
     /*  try{
       String EMAIL_PATTERN="[a-zA-Z0-9] {1,25}@[a-zA-Z0-9]{1,20}.[a-zA-Z{2,3}]";
       Pattern pattern = Pattern.compile(EMAIL_PATTERN);
       
       Matcher regexMatcher = pattern.matcher(jTextFieldEmail.getText());
       if(!regexMatcher.matches()){
           JOptionPane.showMessageDialog(null, "WHAAT");
       }}
       catch (IOException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       else if JOptionPane.showMessageDialog(null,"");
       */
       
       
       //CHECKS SO IMAGE HAS TO SELECTED.
       if(imagePth != null){
           
       
       
       try{
           Path pth = Paths.get(imagePth); 
           img = Files.readAllBytes(pth);
           
            contact c = new contact(null, fname, lname, groupc, phone, lname, address, img, currentUserId);
            contactQuery cq = new contactQuery();
            cq.insertContact(c);
            refreshJtable();
            clearFields();

       }  
       catch (IOException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
          else{
           JOptionPane.showMessageDialog(null, "You have to Select a Profile Picture for contact!");
       }
     
    }//GEN-LAST:event_jButtonAddContactActionPerformed
               // /input Vlidation - THIS VERIFDATA CHECKS ALL DATA IN THE FORM TO MAKE SURE ITS FILLED OUT
    public boolean verifData(){
            //IF USERNAME - FIRST NAME - LAST NAME - PASSWORD ARE EMPTY
            if(jTextFieldFname.getText().equals("") && jTextFieldLname.getText().equals("")
                    || jTextFieldPhone.getText().equals("")
                     )
                    {
                        JOptionPane.showMessageDialog(null,"One or more fields are NOT filled in correctly");
            return false;
        }
            
            
            //IF THERES NO IMAGE SELECTED
            else if(imagePth == null)
            {
                  JOptionPane.showMessageDialog(null,"No Image Selected");
                return false;
            } 
            
            
            //IF ALL FILLED IN RIGHT, ELSE - EVERYTHING IS FINE.
            else{
            return true;
        }
    }
    
    
    
    
    
    
    
    
    
    //################# REFRESHES AFTER ALL EDITS, ADDS AND DELETES ###########
    
    public void refreshJtable(){
        jTable1.setModel(new DefaultTableModel());
   
        populateJtable();
    }
    
    //WHEN A CONTACT IS DELETED, THEIR INFO STAYS THERE UNTIL ANOTHER CONTACT IS SELECTED
    //THIS GETS RID OF THIS ISSUE BELOW.
    public void clearFields(){
        
        jTextFieldId.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("");
        jTextAreaAddress.setText("");
        jComboBoxGroup.setSelectedIndex(0);
        jLabelContactPic.setIcon(null);
        imagePth = null;
    }
    
    
    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditContactActionPerformed
        int id = Integer.valueOf(jTextFieldId.getText());
       String fname = jTextFieldFname.getText();
       String lname = jTextFieldLname.getText();
       String phone = jTextFieldPhone.getText();
       String address = jTextAreaAddress.getText();
       String email = jTextFieldEmail.getText();
       String groupc = jComboBoxGroup.getSelectedItem().toString();
       
       //If the user wants to update the data and needs an image to do so.
       if(imagePth != null){
           byte[] img = null;
       
        try {
           
             Path pth = Paths.get(imagePth);
              img = Files.readAllBytes(pth);
              
              //CONNECTS WITH contactQuery.java file - DOES SQL - INSERTS DATA INTO DATABASE AND RETURNS MSG.
              //CONNECTS WITH CONTACT QUERY AND LOOKS TO UPDATECONTACT METHOD.
              contact c = new contact(id, fname, lname, groupc, phone, email, address, img, currentUserId);
                contactQuery cq = new contactQuery();
                cq.updateContact(c, true);
                refreshJtable();
            
        }catch (FileNotFoundException ex){
                        Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
                        
        }  catch (IOException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
         
        else{
               //CONNECTS WITH contactQuery.java file - DOES SQL - INSERTS DATA INTO DATABASE AND RETURNS MSG.
           //CONNECTS WITH CONTACT QUERY AND LOOKS TO UPDATECONTACT METHOD. PIC TO NULL IF CHANGED
           contact c = new contact(id, fname, lname, groupc, phone, email, address, null, currentUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c, false); 
                
                }
           
    }//GEN-LAST:event_jButtonEditContactActionPerformed
    //VALIDATION - ONLY ACCEPTS NUMBERS
    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please only enter Numerical Values");
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped
    }
    private void jTextFieldFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please only enter Alphanumeric characters");
    }//GEN-LAST:event_jTextFieldFnameKeyTyped
    }
    
    private void jTextFieldLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLnameKeyTyped
        // TODO add your handling code here:
           char c=evt.getKeyChar();
        if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please only enter Alphanumeric characters");
    }//GEN-LAST:event_jTextFieldLnameKeyTyped
    }
    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextAreaAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAddressKeyTyped
          char c=evt.getKeyChar();
         if((!Character.isLetterOrDigit(c) & !Character.isSpace(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please only enter Alphanumeric characters");
   clearFields();
         }   
    }//GEN-LAST:event_jTextAreaAddressKeyTyped

    
    
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyContactsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddContact;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonDeleteContact;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContactPic;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
